# This is your new ~/.config/hypr/hypridle.conf
general {
    before_sleep_cmd = hyprlock  # Lock before suspending
}

listener {
    timeout = 500
    on-timeout = notify-send "Mighty Tired Boss"
}
listener {
    timeout = 600
    on-timeout = hyprlock
}
# This listener will suspend the system after 10 minutes (600 seconds) of idle
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
