
[urgency_low]
    background = "#828282"
    foreground = "#FCFCFC"
    frame_color = "#828282"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#2B2B2B"
    foreground = "#FCFCFC"
    frame_color = "#2B2B2B"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5
